name: Install w/ requirements.txt

on: [push, pull_request]

jobs:
  install-repo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: install with requirements.txt
      run: pip install -r requirements.txt

    - name: run preamble to test
      run: |
        python --version
        python src/preamble.py
